on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check and update CVE records
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate and submit CVE records
        uses: ./ # Uses an action in the root directory
        with:
          cve-user:         ${{ secrets.CVE_USER }}
          cve-org:          ${{ secrets.CVE_ORG }}
          cve-api-key :     ${{ secrets.CVE_API_KEY }}
          cve-environment:  test
          path:             test-cves
          publish:          ${{ github.ref == 'refs/heads/main' }}
          ignore:           published_in_path
          pr:               ${{ github.ref == 'refs/heads/main' }}
          github-token:     ${{ secrets.GITHUB_TOKEN }}
